### ISSUE TITLE
Put xml docs into nuget packages

### ISSUE THREAD

**Issue by dzmitry-lahoda** [jtmueller/Collections.Pooled#1]
so we clear read on what does copy-allocate and what is not.

**Comment by jtmueller** [comment]
Good idea. This is actually already done in the pooled-dictionary branch, but I should have done it on master.

**Comment by jtmueller** [comment]
Merged the pooled-dictionary branch, published NuGet package 1.0.2. Package should now include XML doc files, such as they are.
